fix: Doc hygen global install
echobind/hygen-echobind-templates pull request #3
Opened 2019-11-04 17:28 UTC by cmejet

Update readme direction around `hygen` global install (issue #2 )
Provide more clarity to install the package globally.
Seemed to be easily missed in following the docs.

2019-11-04 17:32 UTC, cball requested changes

2019-11-04 17:32 UTC, cball commented on README.md
> +   If command not found follow the [quick start guide](http://www.hygen.io/quick-start).
are we able to do this in such a way that we keep as a dev dependency and always execute via `yarn hygen`?

2019-11-18 15:08 UTC, cmejet commented
@jsjoeio do you think we can close this PR now that we have added eb-scripts to the template? This would no longer be necessary, correct?

2019-11-18 15:40 UTC, jsjoeio commented
@cmejet yes, probably! Note, I have not looked much at this repo. `eb-scripts` has not replaced these templates yet, but I'm sure it will so you're probably good to close!

2019-11-19 15:22 UTC, closed without merging